### ISSUE TITLE
Plugin refuses to load on 1.20.6

### ISSUE THREAD

**Issue by CloudeLecaw** [Crazy-Crew/BlockParticles#28]
### Plugin Version

1.11.1

### Server Version

1.20.5

### Server Platform

Paper

### Describe the bug

Server is paper 1.20.6

The plugin refuses to load at the moment.
```
[23:56:53] [Server thread/INFO]: [BlockParticles] Enabling BlockParticles v1.11.1-RELEASE
[23:56:53] [Server thread/INFO]: [BlockParticles] [STDOUT] [BlockParticles] Loading the config.yml
[23:56:53] [Server thread/WARN]: Nag author(s): '[BadBones69, Felux]' of 'BlockParticles v1.11.1-RELEASE' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[23:56:53] [Server thread/INFO]: [BlockParticles] [STDOUT] [BlockParticles] Successfully loaded config.yml
[23:56:53] [Server thread/INFO]: [BlockParticles] [STDOUT] [BlockParticles] Loading the data.yml
[23:56:53] [Server thread/INFO]: [BlockParticles] [STDOUT] [BlockParticles] Successfully loaded data.yml
[23:56:53] [Server thread/ERROR]: Error occurred while enabling BlockParticles v1.11.1-RELEASE (Is it up to date?)
java.lang.NumberFormatException: For input string: "craftbukkit"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Integer.java:588) ~[?:?]
	at java.base/java.lang.Integer.parseInt(Integer.java:685) ~[?:?]
	at BlockParticles_1.11.1.jar/me.badbones69.blockparticles.multisupport.Version.getCurrentVersion(Version.java:33) ~[BlockParticles_1.11.1.jar:?]
	at BlockParticles_1.11.1.jar/me.badbones69.blockparticles.api.ParticleManager.load(ParticleManager.java:40) ~[BlockParticles_1.11.1.jar:?]
	at BlockParticles_1.11.1.jar/me.badbones69.blockparticles.BlockParticles.onEnable(BlockParticles.java:33) ~[BlockParticles_1.11.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[23:56:53] [Server thread/INFO]: [BlockParticles] Disabling BlockParticles v1.11.1-RELEASE
[23:56:53] [Server thread/ERROR]: Error occurred while disabling BlockParticles v1.11.1-RELEASE
java.lang.NullPointerException: Cannot invoke "me.badbones69.blockparticles.controllers.ParticleControl.getLocations()" because the return value of "me.badbones69.blockparticles.api.ParticleManager.getParticleControl()" is null
	at BlockParticles_1.11.1.jar/me.badbones69.blockparticles.Methods.kill(Methods.java:80) ~[BlockParticles_1.11.1.jar:?]
	at BlockParticles_1.11.1.jar/me.badbones69.blockparticles.BlockParticles.onDisable(BlockParticles.java:27) ~[BlockParticles_1.11.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-88-980cff9]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### Crate Type

None

### Steps to reproduce

1. start paper server with the plugin on its latest version

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
The plugin is archived pending a re-write, It will not boot on 1.20.6 for a while

**Comment by ryderbelserion** [comment]
I changed my mind, Here is your 1.20.6 update

https://hangar.papermc.io/CrazyCrew/BlockParticles/versions/1.2
